/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as irbtOracleSol from "./IRBTOracle.sol";
export type { irbtOracleSol };
export type { RBTOracle } from "./RBTOracle";
