/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as irbtOracleSol from "./IRBTOracle.sol";
export { RBTOracle__factory } from "./RBTOracle__factory";
